"""
Django settings for Technopro project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lm@(o$_(mb$nn!vq*xje7@f1dsj9r9^c+55jhtylrr6f#bqz(1'

# SECURITY WARNING: don't run with debug turned on in production!
# 本番環境ではDEBUGスイッチをFalseにする
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = []
if not DEBUG :
    ALLOWED_HOSTS = ['team-shiny-99-99-9299.tk']


# Application definition

INSTALLED_APPS = [
    'bs4',
    'selenium',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Technopro',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Technopro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Technopro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
if not DEBUG :
    del DATABASES

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# 投稿ファイル名(基準ファイル)
# ※ このプログラムを最初に動かす前に、予めこのファイルを投稿しておいてください
# ※ このプログラムでスコアが改善した場合、このファイルの内容が書き換わります
SUBMISSION_FILE = "submission.csv"

# 探索ウェイポイントリストファイル名
WPLIST_FILE = "wplist.txt"

# 各種ファイルアップロードディレクトリパス
DIR = STATIC_ROOT

# SIGNATEの投稿結果スコア一覧URL
URL = "https://signate.jp/competitions/102/submissions"

# SIGNATEのアカウント情報
EMAIL = "il.piccola.estate@gmail.com"
PASSWORD = "5qpdc4f6"

# SIGNATEのコンペID
COMPETITION_ID = 102

# 基準の緯度経度
NE_A = [37.5, 125.0]
NE_B = [32.5, 125.0]
NE_C = [40.0, 147.0]
NE_D = [32.5, 145.0]

# -------------------------------------------------------

# 作業ディレクトリパス
WORKDIR = os.path.join(DIR, "work")
os.makedirs(WORKDIR, exist_ok=True)

# 投稿ファイル行対応ウェイポイントファイル名
WAYPOINT_FILE = "waypoint.csv"

# 作業進捗ファイル名
PROGRESS_FILE = "progress.txt"

# ベストスコアファイル名
BESTSCORE_FILE = "bestscore.txt"

# 検索完了リストファイル名
WPLISTFIN_FILE = "wplist_fin.csv"

# 角度データファイル名
ANGLE_FILE_A = "dd2angle_A01_10.csv"
ANGLE_FILE_B = "dd2angle_B_08.csv"
ANGLE_FILE_C = "dd2angle_C_M08.csv"
ANGLE_FILE_D = "dd2angle_D_M10.csv"

# SIGNATEスコア取得コマンド名
SIGNATE_PY = os.path.join(Path(__file__).resolve().parent, "signate.py")
SIGNATE_COM = "python " + SIGNATE_PY
if not DEBUG :
    SIGNATE_COM = "/home/ec2-user/.pyenv/shims/" + SIGNATE_COM

# プロセス起動判定ファイル名
PROCESS_FILE = "process.txt"
